/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../constants/data`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/images`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/icons`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}/firebase/firebaseConfig` | `/firebase/firebaseConfig`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}/firebase/firestore` | `/firebase/firestore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/base-page` | `/base-page`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}/base-page` | `/base-page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../constants/data`; params?: Router.UnknownOutputParams; } | { pathname: `/../constants/images`; params?: Router.UnknownOutputParams; } | { pathname: `/../constants/icons`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(root)'}/firebase/firebaseConfig` | `/firebase/firebaseConfig`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(root)'}/firebase/firestore` | `/firebase/firestore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/sign-in` | `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/base-page` | `/base-page`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(root)'}/base-page` | `/base-page`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(root)'}/sign-in` | `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/../constants/data${`?${string}` | `#${string}` | ''}` | `/../constants/images${`?${string}` | `#${string}` | ''}` | `/../constants/icons${`?${string}` | `#${string}` | ''}` | `${'/(root)'}/firebase/firebaseConfig${`?${string}` | `#${string}` | ''}` | `/firebase/firebaseConfig${`?${string}` | `#${string}` | ''}` | `${'/(root)'}/firebase/firestore${`?${string}` | `#${string}` | ''}` | `/firebase/firestore${`?${string}` | `#${string}` | ''}` | `${'/(root)'}${'/(tabs)'}/sign-in${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `${'/(root)'}${'/(tabs)'}/base-page${`?${string}` | `#${string}` | ''}` | `/base-page${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(root)'}/base-page${`?${string}` | `#${string}` | ''}` | `/base-page${`?${string}` | `#${string}` | ''}` | `${'/(root)'}/sign-in${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `${'/(root)'}${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(root)'}${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../constants/data`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/images`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/icons`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}/firebase/firebaseConfig` | `/firebase/firebaseConfig`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}/firebase/firestore` | `/firebase/firestore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/base-page` | `/base-page`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}/base-page` | `/base-page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; };
    }
  }
}
